// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:642b14b5-296d-4571-9767-df83c3ad118e",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_v7bKcvQ4u",
    "aws_user_pools_web_client_id": "1omr9afeoio87nhml4u76249ji",
    "oauth": {
        "domain": "fire593d548d-593d548d-dev.auth.us-east-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:4200/signedIn/",
        "redirectSignOut": "http://localhost:4200/signedOut/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;